### ISSUE TITLE
Body landmarks in edge mode

### ISSUE THREAD

**Issue by mateomotriz** [geaxgx/depthai_hand_tracker#15]
Hello, I'm trying to implement your handtracker including the body landmarks given by the Movenet model, in Edge mode;

is there a reason why you hadn't include them in the edge mode? the 'bag' is always empty, so there's no additional info appart from the hand landmarks;

thanks in advance and absolutely stunning work!!

**Comment by geaxgx** [comment]
Hi,
Initially, visualizing the body landmarks was useful for me when implementing and debugging the body pre focusing mode. I decided to keep it in host mode just because I thought it could be useful for users for a better understanding of the bpf mode, and also in this mode, there is no impact on perfomance. It is not implemented in edge mode to minimize the size of the data transferred on the USB link.

**Comment by mateomotriz** [comment]
Ok thats perfect, thanks for the answer!
