### ISSUE TITLE
use of mono camera instead of rgb for hands

### ISSUE THREAD

**Issue by clementshimizu** [geaxgx/depthai_hand_tracker#16]
I know the media pipe hands works best with rgb, but i think it will still work in mono even if i have to just convert the mono image to rgb by duplicating the channel 3 times.

OAKD pro includes a IR blanket illuminator.  I have OAKD with a separate IR blanket illuminator.

"Blanket IR LED illumination allows perceiving low-light and no-light environments. You can run your AI/CV processes on frames that are illuminated by the IR LED. Note that the color camera doesn’t perceive IR light, so you would need to use a mono camera stream for your AI/CV processes."

Now to get this to work with this sample, i would like to use the left or right mono camera instead of the RGB camera.  

There is no option for mono in the HandTrackerBpf.py and my first try at replacing the line 

            cam = pipeline.createColorCamera()
            cam.setResolution(dai.ColorCameraProperties.SensorResolution.THE_1080_P)
            cam.setBoardSocket(dai.CameraBoardSocket.RGB)
            
            with 
            
            cam = pipeline.create(dai.node.MonoCamera)
            cam .setBoardSocket(dai.CameraBoardSocket.LEFT)
            cam .setResolution(dai.MonoCameraProperties.SensorResolution.THE_720_P)

This doesn't work because the createColorCamera object has a very different structure to what pipeline.create(dai.node.MonoCamera) returns.  So I think a new branch of the program needs to be done to handle this.  If you have an idea how to do that i think it would be very useful for low light applications.

**Comment by geaxgx** [comment]
In the past, I did some tests with gray level video or images. Unfortunately, it is very disappointing, mainly because the palm detector has hard time to find palms in gray images. The landmark regressor seems to be less penalized but as the former kick-starts the latter, the global result is not good. 
That's something you can easily try in host mode by using a video or a webcam as input.
FIrst after: https://github.com/geaxgx/depthai_hand_tracker/blob/c803ad33437637d06c25fd44e5c3ef7c8760ff1e/HandTracker.py#L509
add:
`frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY);
 frame = cv2.cvtColor(frame, cv2.COLOR_GRAY2BGR)`
and run:
`./demo.py -i 0` to use a webcam as input or `./demo.py -i 0 --no_lm` to run only the palm detector.

But surprisingly, the OAK-D's RGB sensor is doing a pretty good job under low light. Watch this video where the scene is just lit by the computer screen: https://www.youtube.com/watch?v=7wCWtuxaXZ8&ab_channel=geaxgx1
Note however, that with such hard conditions, the hands need to stay close to the camera.

**Comment by geaxgx** [comment]
Closing as stale. Please reopen if you'd like to work on this further.
